### ISSUE TITLE
project_cfg.h  struct name error

### ISSUE THREAD

**Issue by chopin1998** [kendryte/kendryte-freertos-demo#1]
should be?

const pin_cfg_t g_io_cfg =
{
    .version = PIN_CFG_VERSION,
    .set_spi0_dvp_data = 1
};

**Comment by ly0** [comment]
Which demo are you using?

**Comment by chopin1998** [comment]
the lcd demo

**Comment by sunnycase** [comment]
`g_pin_cfg` is right. Please use the newest SDK.
